name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python
  - python=3.10
  - numpy>=1.23,<2.0
  - pandas>=1.5,<2.0
  - scipy
  - click
  - pyyaml
  - rich
  - tqdm
  - matplotlib
  
  # MD-Stack (nur das Nötigste)
  - gromacs=2024.5
  - vermouth
  
  # Trajektorien-Analyse
  - mdtraj
  - mdanalysis
  
  # PyTorch (für FastFold)
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  
  # FastFold Dependencies
  - dm-tree
  - ml-collections
  
  # pip packages
  - pip
  - pip:
    - -e external/fastfold
    - -e . 