name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  # Core Python & Scientific Stack
  - python=3.10
  - numpy>=1.23,<2.0  # Kompatibilit채t mit FastFold
  - pandas>=1.5,<2.0
  - scipy
  - click
  - pyyaml
  - rich
  - tqdm
  - matplotlib
  - mlflow
  - moviepy
  
  # MD-Stack
  - gromacs=2024          # GPU-f채higes GROMACS
  - vermouth              # martinize2-Dependency
  
  # System Tools
  - aria2                 # F체r Datenbank-Downloads
  - wget
  - curl
  
  # Dev / Tests
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort
  - pip
  - pip:
      # GPU-Stack (PyTorch mit CUDA 12.1)
      - torch==2.3.0+cu121
      - torchvision
      - torchaudio
      - --index-url https://download.pytorch.org/whl/cu121
      
      # FastFold & Dependencies
      - dm-tree
      - ml_collections
      - colossalai
      - einops
      
      # OpenFold
      - openfold
      
      # DeepSpeed
      - deepspeed==0.14.4
      
      # Other Dependencies
      - insane               # Python-Package ersatzweise 체ber pip
      
      # Unser Projekt selber (editable install wenn innerhalb venv)
      - -e . 