name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - gromacs=2024
  - biopython
  - click
  - pyyaml
  - pandas=1.5.3
  - numpy=1.24.3
  - tqdm
  - matplotlib
  - mlflow
  - moviepy
  - rich
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort
  - pip
  - pip:
      # GPU-spezifische Pakete werden separat installiert
      - omegaconf 