name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  # Core Python & Scientific Stack
  - python=3.10
  - numpy>=1.23,<2.0  # Kompatibilität mit FastFold
  - pandas>=1.5,<2.0
  - scipy
  - click
  - pyyaml
  - rich
  - tqdm
  - matplotlib
  - mlflow
  - moviepy
  
  # MD-Stack
  - gromacs=2024          # GPU-fähiges GROMACS
  - vermouth              # martinize2-Dependency
  
  # Trajektorien-Analyse (echte Implementierungen)
  - mdtraj                # Für Trajektorien-Analyse
  - mdanalysis            # Für Pore-Detektion und Thinning-Analyse
  
  # System Tools
  - aria2                 # Für Datenbank-Downloads
  - wget
  - curl
  - git
  
  # Development Tools
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  
  # PyTorch mit CUDA 12.1 Support
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  
  # Deep Learning & Optimization
  - deepspeed
  - accelerate
  
  # FastFold/OpenFold Dependencies
  - dm-tree
  - ml-collections
  
  # Additional Scientific Libraries
  - biopython
  - networkx
  - scikit-learn
  
  # Visualization
  - seaborn
  - plotly
  
  # pip packages (nach conda installieren)
  - pip
  - pip:
    # FastFold als Git-Submodul installieren
    - -e external/fastfold
    # OpenFold als Git-Submodul installieren  
    - -e external/openfold
    # Projekt selbst installieren
    - -e . 