name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  # Core
  - python=3.10
  - numpy>=1.23,<2.0
  - pandas>=1.5,<2.0
  - scipy
  - click
  - pyyaml
  - rich
  - tqdm
  - matplotlib
  - mlflow
  - moviepy
  # MD-Stack
  - gromacs=2024          # GPU-fähiges GROMACS
  - vermouth              # martinize2-Dependency
  # GPU-Stack (torch via pip nach der Env-Aktivierung installieren)
  # - pytorch=2.3.*=cuda121*
  # - pytorch-cuda=12.1     # get rid – nutzen wir Pip-Wheels
  #  - cudnn=8.9  # optional, falls System-Bibliotheken benötigt werden
  # Dev / Tests
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort
  - pip
  - pip:
      # FastFold / OpenFold nachträglich installieren, wenn Torch vorhanden
      # z.B.:
      # pip install torch==2.3.0+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
      # pip install openfold fastfold
      - deepspeed==0.14.4
      - insane               # Python-Package ersatzweise über pip
      # Unser Projekt selber (editable install wenn innerhalb venv)
      - -e . 