from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Sequence

import yaml

from .utils import LOGGER, ensure_dir

CONFIG = yaml.safe_load(Path("config/system.yaml").read_text())


def build(profile: str, peptide_gro: str | Path, out_dir: str | Path) -> Path:
    """Baue eine Lipidmembran mithilfe von insane.py oder Dummy-Version."""
    out_dir = ensure_dir(out_dir)
    system_gro = Path(out_dir) / "membrane.gro"
    lipids = CONFIG.get(profile, CONFIG["default"])  # type: ignore[index]

    cmd: Sequence[str] = [
        "insane",
        "-f",
        str(peptide_gro),
        "-o",
        str(system_gro),
        "-l",
        ",".join(f"{l['name']}:{l['ratio']}" for l in lipids["lipids"]),
    ]

    try:
        LOGGER.info("Baue Membran mit insane.py: %s", " ".join(cmd))
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except (FileNotFoundError, subprocess.CalledProcessError):
        LOGGER.warning("insane.py nicht verfügbar, erstelle Dummy-Membran.")
        system_gro.write_text(
            "Generated by amp-rbc-md - dummy membrane\n   0\n   1W        OW    1   0.000   0.000   0.000\n   1.0\n"
        )
    return system_gro


__all__ = ["build"]
