from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Sequence

import yaml

from .utils import LOGGER, ensure_dir

CONFIG = yaml.safe_load(Path("config/system.yaml").read_text())


def build(profile: str, peptide_gro: str | Path, out_dir: str | Path) -> Path:
    """Baue eine Lipidmembran mithilfe von insane.py oder Dummy-Version."""
    out_dir = ensure_dir(out_dir)
    system_gro = Path(out_dir) / "membrane.gro"
    lipids = CONFIG.get(profile, CONFIG["default"])  # type: ignore[index]

    cmd: Sequence[str] = [
        "insane",
        "-f",
        str(peptide_gro),
        "-o",
        str(system_gro),
        "-l",
        ",".join(f"{l['name']}:{l['ratio']}" for l in lipids["lipids"]),
    ]

    try:
        LOGGER.info("Baue Membran mit insane.py: %s", " ".join(cmd))
        result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        LOGGER.info("insane erfolgreich ausgeführt")
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        LOGGER.warning("insane.py nicht verfügbar (%s), erstelle Dummy-Membran.", e)
        system_gro.write_text("""Generated by amp-rbc-md - dummy membrane
    4
    1PEPT     BB    1   0.000   0.000   0.000
    2PEPT     BB    2   0.000   0.000   0.350
    3POPC     PO    3   1.000   1.000   1.000
    4CHOL     ROH   4   2.000   2.000   2.000
   10.0  10.0  10.0
""")
    return system_gro


__all__ = ["build"]
