from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Sequence

from .utils import LOGGER, ensure_dir


def martinize(
    pdb: str | Path, out_dir: str | Path, elastic: int = 0
) -> tuple[Path, Path]:
    """Rufe martinize2 auf, um CG-Topologie & -Struktur zu erstellen.

    Für die Testumgebung wird, falls martinize2 nicht verfügbar ist, ein Dummy-Top
    und .gro erzeugt.
    """
    out_dir = ensure_dir(out_dir)
    top_path = Path(out_dir) / "system.top"
    gro_path = Path(out_dir) / "system.gro"

    cmd: Sequence[str] = [
        "martinize2",
        "-f",
        str(pdb),
        "-o",
        str(top_path),
        "-x",
        str(gro_path),
        "--elastic",
        str(elastic),
    ]
    try:
        LOGGER.info("Führe martinize2 aus: %s", " ".join(cmd))
        result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        LOGGER.info("martinize2 erfolgreich ausgeführt")
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        LOGGER.warning("martinize2 nicht verfügbar (%s), erstelle Dummy-Dateien.", e)
        top_path.write_text("; dummy topology\n[ system ]\nPeptide\n")
        gro_path.write_text(
            "Generated by amp-rbc-md\n   0\n   1W        OW    1   0.000   0.000   0.000\n   1.0\n"
        )

    return gro_path, top_path


__all__: list[str] = ["martinize"]
