from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Sequence

from .utils import LOGGER, ensure_dir


def martinize(
    pdb: str | Path, out_dir: str | Path, elastic: int = 0
) -> tuple[Path, Path]:
    """Rufe martinize2 auf, um CG-Topologie & -Struktur zu erstellen.

    Für die Testumgebung wird, falls martinize2 nicht verfügbar ist, ein Dummy-Top
    und .gro erzeugt.
    """
    out_dir = ensure_dir(out_dir)
    top_path = Path(out_dir) / "system.top"
    gro_path = Path(out_dir) / "system.gro"

    cmd: Sequence[str] = [
        "martinize2",
        "-f",
        str(pdb),
        "-o",
        str(top_path),
        "-x",
        str(gro_path),
        "--elastic",
        str(elastic),
    ]
    try:
        LOGGER.info("Führe martinize2 aus: %s", " ".join(cmd))
        result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        LOGGER.info("martinize2 erfolgreich ausgeführt")
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        LOGGER.warning("martinize2 nicht verfügbar (%s), erstelle Dummy-Dateien.", e)
        top_path.write_text("""; dummy topology
[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
1               2               yes             1.0     1.0

[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
BB        0         72.0    0.0    A      0.47       9.4e-3
PO        0         92.0   -1.0    A      0.47       9.4e-3
ROH       0         386.0   0.0    A      0.47       9.4e-3

[ moleculetype ]
; Name            nrexcl
Peptide          1

[ atoms ]
;   nr   type  resnr residue  atom   cgnr     charge       mass  typeB    chargeB      massB
     1     BB      1    PEPT     BB      1        0.000     72.000
     2     BB      2    PEPT     BB      2        0.000     72.000

[ bonds ]
;  ai    aj funct            c0            c1            c2            c3
    1     2     1

[ moleculetype ]
; Name            nrexcl
POPC           1

[ atoms ]
;   nr   type  resnr residue  atom   cgnr     charge       mass  typeB    chargeB      massB
     1     PO      1   POPC     PO      1       -1.000     92.000

[ moleculetype ]
; Name            nrexcl
CHOL           1

[ atoms ]
;   nr   type  resnr residue  atom   cgnr     charge       mass  typeB    chargeB      massB
     1    ROH      1   CHOL    ROH      1        0.000    386.000

[ system ]
Peptide in membrane

[ molecules ]
; Compound        nmols
Peptide              1
POPC                 1
CHOL                 1
""")
        gro_path.write_text("""Generated by amp-rbc-md
    2
    1PEPT     BB    1   0.000   0.000   0.000
    2PEPT     BB    2   0.000   0.000   0.350
   3.0   3.0   3.0
""")

    return gro_path, top_path


__all__: list[str] = ["martinize"]
