name: GPU-SMOKE

on:
  workflow_dispatch:

jobs:
  gpu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t amp-rbc-md:gpu .
      - name: Run Smoke
        run: |
          docker run --gpus all --rm amp-rbc-md:gpu amp-rbc-md run_sim --seq GLSILGKLL --n-replica 1 --time 100ps --dry-run 